server:
  port: 8082

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27012}
      database: ${MONGO_DATABASE:uploads}

  boot:
    admin:
      client:
        url: ${ADMIN_CLIENT_URL:http://localhost:8082}
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: logs/client.log
    path: logs
